BookTourismWeb/Controllers/BookingController.cs
using BookTourismClassLibrary;
using BookTourismClassLibrary.BookingManagement;
using BookTourismClassLibrary.TourManagement;
using BookTourismClassLibrary.UserManagement;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BookTourismWeb.Controllers
{
    public class BookingController : Controller
    {
        private readonly DbContextClass db = new DbContextClass();
        // GET: Booking
        public ActionResult BookTrip(int id)
        {
            User user = (User)Session[WebUtil.CURRENT_USER];
            if (user == null)
            {
                return RedirectToAction("Login", "User");
            }

            Tour tour = new TourHandler().GetTourById(id);
            ViewBag.HideSlider = true;
            return View(tour);
        }

        public ActionResult BookingConfirmed(int id)
        {
            User user = (User)Session[WebUtil.CURRENT_USER];
            if (user == null)
            {
                return RedirectToAction("Login", "User");
            }
            Tour tour = new TourHandler().GetTourById(id);

            Booking booking = new Booking
            {
                Tour = tour,
                UserId = user.Id
            };

            new BookingHandler().AddBooking(booking);
            ViewBag.HideSlider = true;
            return View();
        }

        public ActionResult BookingList()
        {
            List<Booking> bookings = new BookingHandler().GetAllBookings();
            return View(bookings);
        }

        public ActionResult Delete(int? id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Booking booking = new BookingHandler().GetBookingById(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }

        // POST: History/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Booking booking = new BookingHandler().GetBookingById(id);
            db.Entry(booking.Tour).State = EntityState.Unchanged;
            db.Entry(booking.User).State = EntityState.Unchanged;
            db.Entry(booking).State = EntityState.Deleted;
            db.Bookings.Remove(booking);
            db.SaveChanges();
            return RedirectToAction("BookingList");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public int GetBokingCount()
        {
            return (new BookingHandler().BookingCount());
        }
    }
}

BookTourismWeb/Controllers/CompanyController.cs
using BookTourismClassLibrary;
using BookTourismClassLibrary.CompanyManagement;
using BookTourismClassLibrary.LocationManagement;
using BookTourismClassLibrary.UserManagement;
using BookTourismWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookTourismWeb.Controllers
{
    public class CompanyController : Controller
    {
        // GET: Company
        public ActionResult CompanyManagment()
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
            }
            List<Company> companies = new CompanyHandler().GetAllCompanies();

            ViewBag.message = TempData["message"];

            return View(companies);
        }

        // GET: Company/Details/
        public ActionResult CompanyDetails(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Company company = new CompanyHandler().GetCompanybyId(id);
            return View(company);
        }

        // GET: Company/Create
        public ActionResult AddCompany()
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            LocationHandler lh = new LocationHandler();
            ViewBag.CountryList = ModelHelper.ToSelectItemList(lh.GetCountries());
           // ViewBag.voters = new SelectList(ModelHelper.ToSelectItemList(lh.GetCountries), "VoterId", "StaffName");
            return View();
        }

        // POST: Company/Create
        [HttpPost]
        public ActionResult AddCompany(FormCollection fdata)
        {

            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            LocationHandler lh = new LocationHandler();
            ViewBag.CountryList = ModelHelper.ToSelectItemList(lh.GetCountries());
            try
            {
                Company c = new Company
                {
                    Name = fdata["Name"],
                    Description = fdata["Description"],
                    FacebookPageUrl = fdata["FacebookPageUrl"],
                    City = new City { Id = Convert.ToInt32(fdata["CityList"]) }
                };
                long numb = DateTime.Now.Ticks;
                int count = 0;
                foreach (string fname in Request.Files)
                {
                    HttpPostedFileBase file = Request.Files[fname];
                    if (!string.IsNullOrEmpty(file?.FileName))
                    {
                        string url = "/ImagesData/CompanyImages/" + numb + "_" + ++count + file.FileName.Substring(file.FileName.LastIndexOf(".", StringComparison.Ordinal));
                        string path = Request.MapPath(url);
                        file.SaveAs(path);
                        c.ImageUrl = url;
                    }
                    else
                    {
                        string url = "/ImagesData/CompanyImages/noimage2.jpg";
                        c.ImageUrl = url;
                    }
                }
                new CompanyHandler().AddCompany(c);
                return RedirectToAction("CompanyManagment");
            }
            catch
            {
                return View();
            }
        }

        // GET: Company/Edit/
        public ActionResult EditCompany(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Company company = new CompanyHandler().GetCompanybyId(id);
            return View(company);
        }

        // POST: Company/Edit/5
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult EditCompany(Company company)
        {
            try
            {
                User u = (User)Session[WebUtil.CURRENT_USER];
                if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
                {
                    return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
                }

                if (ModelState.IsValid)
                {
                    new CompanyHandler().UpdateCompany(company);
                    return RedirectToAction("CompanyManagment");
                }
                return View(company);
            }
            catch
            {
                return View();
            }
        }

        // GET: Company/Delete/5
        public ActionResult DeleteCompany(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Company company = new CompanyHandler().GetCompanybyId(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Company/Delete/5
        [HttpPost, ActionName("DeleteCompany")]
        public ActionResult DeleteCompanyConfirmed(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            try
            {
                Company company = new CompanyHandler().GetCompanybyId(id);
                new CompanyHandler().DeleteCompany(company);
                return RedirectToAction("CompanyManagment");
            }
            catch
            {
                ViewBag.message = "Cannot Delete. This Company Is Assigned To Some Tour. Delete That Tour First";
                TempData["message"] = ViewBag.message;
                return RedirectToAction("CompanyManagment");
            }
        }

        public int GetCompanyCount()
        {
            return new CompanyHandler().GetCompanyCount();
        }
    }
}

BookTourismWeb/Controllers/TourController.cs
using BookTourismClassLibrary;
using BookTourismClassLibrary.CompanyManagement;
using BookTourismClassLibrary.TourManagement;
using BookTourismClassLibrary.UserManagement;
using BookTourismWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookTourismWeb.Controllers
{
    public class TourController : Controller
    {
        // GET: Tour
        public ActionResult TourManagment()
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
            }
            List<Tour> tours = new TourHandler().GetAllTours();
            ViewBag.message = TempData["message"];
            return View(tours);
        }

        public ActionResult TourDetails(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Tour tour = new TourHandler().GetTourById(id);
            return View(tour);
        }

        [HttpGet]
        public ActionResult AddTour()
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            ViewBag.companies = ModelHelper.ToSelectItemList(new CompanyHandler().GetAllCompanies());
            return View();
        }

        [HttpPost]
        public ActionResult AddTour(FormCollection fdata)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Product", act = "AddProduct" });
            }
            try
            {
                Tour t = new Tour
                {
                    Title = fdata["Title"],
                    Description = fdata["Description"], //.Replace(" ", "&nbsp;").Replace("\n", "<br>"),
                    Price = Convert.ToSingle(fdata["Price"]),
                    Sale = Convert.ToSingle(fdata["Sale"]),
                    Company = new Company { Id = Convert.ToInt32(fdata["CompanyList"]) },
                    DepartureDate = fdata["DepartureDate"]
                };
                long numb = DateTime.Now.Ticks;
                int count = 0;

                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    if (file != null && file.ContentLength > 0)
                    {
                        string name = file.FileName;
                        string url = "/ImagesData/TourImages/" + numb + "_" + ++count +
                                     file.FileName.Substring(file.FileName.LastIndexOf("."));
                        string path = Request.MapPath(url);
                        file.SaveAs(path);
                        t.TourImages.Add(new TourImages() { Caption = name, ImageUrl = url });
                    }
                    else
                    {
                        string name = "No Image";
                        string url = "/ImagesData/TourImages/noimage2.jpg";
                        t.TourImages.Add(new TourImages { Caption = name, ImageUrl = url });
                    }
                }

                new TourHandler().AddTour(t);
                return RedirectToAction("TourManagment");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult EditTour(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Tour tour = new TourHandler().GetTourById(id);
            ViewBag.companies = ModelHelper.ToSelectItemList(new CompanyHandler().GetAllCompanies());
            return View(tour);
        }

        // POST: Company/Edit/5
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult EditTour([Bind(Include = "Id,Title,Description,Price,Sale,DepartureDate")]Tour tour)
        {
            try
            {
                User u = (User)Session[WebUtil.CURRENT_USER];
                if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
                {
                    return RedirectToAction("Login", "User", new { ctl = "Home", act = "Index" });
                }

                if (ModelState.IsValid)
                {
                    new TourHandler().UpdateTour(tour);
                    return RedirectToAction("TourManagment");
                }
                return View(tour);
            }
            catch
            {
                return View();
            }
        }

        public ActionResult DeleteTour(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            Tour tour = new TourHandler().GetTourById(id);
            if (tour == null)
            {
                return HttpNotFound();
            }
            return View(tour);
        }

        // POST: Tour/Delete/
        [HttpPost, ActionName("DeleteTour")]
        public ActionResult DeleteTourConfirmed(int id)
        {
            User u = (User)Session[WebUtil.CURRENT_USER];
            if (!(u != null && u.IsInRole(WebUtil.ADMIN_ROLE)))
            {
                return RedirectToAction("Login", "User", new { ctl = "Admin", act = "AdminPanel" });
            }
            try
            {
                Tour tour = new TourHandler().GetTourById(id);
                new TourHandler().DeleteTour(tour);


                return RedirectToAction("TourManagment");
            }
            catch
            {
                ViewBag.message = "Cannot Delete. This Tour Is Assigned To Some Booking. Delete That Booking First";
                TempData["message"] = ViewBag.message;
                return RedirectToAction("TourManagment");
            }
        }

        public int GetTourCount()
        {
            return new TourHandler().GetTourCount();
        }
    }
}

BookTourismWeb/Views/Shared/_AdminLayout.cshtml
@using BookTourismClassLibrary
@using BookTourismClassLibrary.UserManagement
@{
    User currentUser = (User)Session[WebUtil.CURRENT_USER];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>🚨 @ViewBag.Title BPT-Admin</title>
    <link href="~/ImagesData/SiteImages/pakistan.png" rel="icon" type="image/x-icon" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <!-- TopBar (NAVBAR) -->
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Left Most Logo and Page TITLE -->
            <div class="navbar-header">
                <!--Collapsable Navbar button for small screens -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#colNav">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Home")" class="navbar-brand">Book <span class="fa fa-ticket"></span> Pakistan T<i class="fa fa-globe" style="font-size:small"></i>ur</a>
            </div>
            <div class="collapse navbar-collapse" id="colNav">
                <!-- Next icons/Lists of Options in Unordered List Type -->
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("HOME", "Index", "Home")</li>
                    <li><a href="@Url.Action("Pakistan","Home")">Pakistan</a></li>
                    <li><a href="@Url.Action("OurTours","Home")">Our Tours</a></li>
                    <li><a href="@Url.Action("Companies","Home")">Travel Companies</a></li>
                    <li><a href="@Url.Action("ContactUs","Home")">Contact Us</a></li>
                    <!-- User Detail Dropdown with custom CSS -->
                    @if (currentUser != null)
                    {
                        <li class="dropdown notextselect">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fa fa-user-circle-o fa-lg"></span> @currentUser.FullName <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <div class="navbar-login">
                                        <div class="row">
                                            <div class="col-lg-4">
                                                <div style="width: 80px; height: 95px">
                                                    <img class="img-responsive img-rounded" style="width: 100%; height: 100%" alt="user-image" src="@Url.Content(currentUser.ImageUrl)" />
                                                </div>
                                            </div>
                                            <div class="col-lg-8">
                                                <p class="text-left"><strong>@currentUser.FullName</strong></p>
                                                <p class="text-left small">@currentUser.Email</p>
                                                <p class="text-left">
                                                    <a href="@Url.Action("UserGuestUpdate","User", new { id = currentUser.Id})" class="btn btn-default btn-block">UPDATE</a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        if (currentUser.IsInRole(WebUtil.ADMIN_ROLE))
                        {
                            <li>@Html.ActionLink("Admin Panel", "AdminPanel", "Admin")</li>
                        }
                    }
                </ul>
                <!-- Nav Bar Right Area Buttons -->
                <ul class="nav navbar-nav navbar-right">
                    @if (currentUser != null)
                    {
                        <li><a href="@Url.Action("Logout", "User")"><span class="glyphicon glyphicon-log-out"></span> Logout </a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("SignUp", "User")"><span class="fa fa-user-plus fa-lg"></span> SignUp</a></li>
                        <li><a href="@Url.Action("Login", "User")"><span class="fa fa-sign-in fa-lg"></span> Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <!-- LEFT SECTION -->
            <div class="col-lg-3">
                <div class="list-group text-center notextselect">
                    <h3 class="list-group-item-heading text-center">ADMIN OPTI<i class="fa fa-gear fa-spin"></i>NS</h3>
                    @*@Html.ActionLink("Overview", "AdminPanel", "Admin", null, new { @class = "list-group-item" })*@
                    <a href="@Url.Action("TourManagment","Tour")" class="list-group-item"> Tours Management <i class="fa fa-globe"></i><i class="badge" style="font-size:x-small; margin-top:2px">@Html.Action("GetTourCount", "Tour")</i></a>
                    <a href="@Url.Action("CompanyManagment","Company")" class="list-group-item">Companies Management <i class="fa fa-building"></i><i class="badge" style="font-size:x-small;margin-top:2px">@Html.Action("GetCompanyCount", "Company")</i></a>
                    <a href="@Url.Action("UserManagment","User")" class="list-group-item"> User Management <i class="fa fa-group"></i><i class="badge" style="font-size:x-small;margin-top:2px">@Html.Action("UserCount", "User")</i></a>
                    <a href="@Url.Action("BannerManagment","Admin")" class="list-group-item"> Main Page Banners <span class="fa fa-image"></span><i class="badge" style="font-size:x-small;margin-top:2px">@Html.Action("GetBannerCount", "Admin")</i></a>
                    <a href="@Url.Action("LocationManagment","Location")" class="list-group-item">Location Management <span class="fa fa-map-marker"></span><span class="badge" style="font-size:x-small;margin-top:2px">@Html.Action("GetCountriesCount", "Location")</span></a>
                    <a href="@Url.Action("Index","History")" class="list-group-item">History Management <span class="fa fa-book"></span><span class="badge" style="font-size:x-small;margin-top:2px">@Html.Action("GetHistoryCount", "History")</span></a>
                    <a href="@Url.Action("BookingList","Booking")" class="list-group-item"> BOOKINGS! <i class="fa fa-ticket"></i><i class="badge" style="font-size:x-small; margin-top:2px">@Html.Action("GetBokingCount", "Booking")</i></a>
                </div>
            </div>
            <!-- RIGHT SECTION -->
            @RenderBody()
        </div>
    </div>
    @*<div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@
    <script src="~/Scripts/jquery-2.2.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("myScript", false)
</body>
</html>

BookTourismWeb/Views/Shared/_CompanySummaryView.cshtml
@model BookTourismClassLibrary.CompanyManagement.Company
@if (Model != null)
{

    <div class="col-lg-4 list-group-item">
        <div class="thumbnail">
            <a href="@Url.Action("CompanyDetails","Home", new { id=Convert.ToInt32(Model.Id) })" class="img-thumbnail text-center center-block" style="text-decoration:none; color: inherit; width: 250px; height: 250px;background-image: url(@Model.ImageUrl); background-size: cover; background-repeat: no-repeat; background-position: 50%;">
                @*<img style="height: 100%" name="sumimg" id="sumig" src="@Url.Content(Model.ImageUrl)" alt="Loading..." />*@ <!--Thumbnail Image (first or Default Image)-->
            </a>
            <div style="height: auto; overflow: hidden; text-align: center; margin: 10px">
                <strong> @Model.Name</strong>
                <p>@Model.City.Country.Name</p> , <p>@Model.City.Name</p>
            </div>
            <hr style="margin: 0" />
            <div class="row">
                <div class="col-lg-12 center-block text-center">
                    <a href="@Url.Action("CompanyDetails","Home", new { id = Convert.ToInt32(Model.Id)})" class="btn btn-default"><span class="fa fa-eye"></span> View History</a>
                </div>
            </div>
        </div>
    </div>
}

BookTourismWeb/Views/Shared/_DDLView.cshtml
@*@using FYProject1.Models
@model FYProject1.Models.DDViewModel
@Html.DropDownList(Model.Name, Model.Values, Model.Label, new { @class = "form-control text-center", style = "Float: Left", name = "CityList" })*@

BookTourismWeb/Views/Shared/_HistorySummaryView.cshtml
@model BookTourismClassLibrary.HistoryManagement.History
@if (Model != null)
{

    <div class="col-lg-4 list-group-item">
        <div class="thumbnail notextselect">
            <a href="@Url.Action("HistoryDetail","Home", new { id=Convert.ToInt32(Model.Id) })" class="img-thumbnail text-center center-block" style="text-decoration:none; color: inherit; width: 250px; height: 250px;background-image: url(@Model.ImageUrl); background-size: cover; background-repeat: no-repeat; background-position: 50%;">
                @*<img style="height: 100%" name="sumimg" id="sumig" src="@Url.Content(Model.ImageUrl)" alt="Loading..." />*@ <!--Thumbnail Image (first or Default Image)-->
            </a>
            <div style="height: auto; overflow: hidden; text-align: center; margin: 10px">
                <strong> @Model.Title</strong>
            </div>
            <hr style="margin: 0" />
            <div class="row">
                <div class="col-lg-12 center-block text-center">
                    <a href="@Url.Action("HistoryDetail","Home", new { id = Convert.ToInt32(Model.Id)})" class="btn btn-default"><span class="fa fa-eye"></span> View History</a>
                </div>
            </div>
        </div>
    </div>
}

BookTourismWeb/Views/Shared/_TourSummaryView.cshtml
@using BookTourismWeb.Models
@model IEnumerable<TourSummaryModel>
@if (Model != null)
{
    foreach (var p in Model)
    {
        <div id="proditem" class="col-lg-4">
            <div class="thumbnail notextselect">
                <a href="@Url.Action("TourDetail","Home", new { id=Convert.ToInt32(p.Id) })" class="img-thumbnail text-center center-block" style="text-decoration:none; color: inherit; width: 250px; height: 250px; background-image: url(@p.ImageUrl); background-size: cover; background-repeat: no-repeat; background-position: 50%;">
                    @*<img style="height: 100%" name="sumimg" id="sumig" src="@Url.Content(p.ImageUrl)" alt="Loading..." />*@ <!--Thumbnail Image (first or Default Image)-->
                </a>
                <small id="company"><a href="@Url.Action("ToursByCompany","Home",new { name = p.Company })" class="text-muted" style="text-decoration:none">@p.Company</a></small> <!-- Brand -->
                @if (p.Sale != 0)
                {
                    <p class="label label-default pull-right">@p.Sale% off</p> <!-- Sale Percentage -->
                }
                <br />
                <div style="height: 40px; overflow: hidden">
                    <strong><i class="glyphicon glyphicon-minus"></i> @p.Title</strong>  <!--Kit Includes-->
                </div>
                <hr style="margin-bottom: 5px; margin-top: 0">
                <div class="row">
                    <div class="col-lg-12">
                        @if (p.Sale != 0)
                        {
                            <div style="height: 63px; display: table; margin: auto">
                                <p class="text-center" style="font-size: 22px;color:#333; display: table-cell; vertical-align: middle"><strike style="font-size:small" class="text-muted">Rs @($"{p.Price:N0}")</strike> Rs @($"{p.Price - (p.Price * p.Sale / 100):N0}")</p>
                            </div>

                        }
                        else
                        {
                            <div style="height: 63px; display: table; margin: auto">
                                <p class="text-center" style="font-size: 22px;color:#333; display: table-cell; vertical-align: middle">Rs @($"{p.Price:N0}")</p> <!-- Price -->
                            </div>

                        }
                    </div>
                    <div class="col-lg-12">
                        <a href="@Url.Action("BookTrip","Booking", new { id = p.Id})" class="btn btn-primary btn-block">BOOK NOW</a>
                    </div>
                </div>
            </div>
        </div>
    }
}